const characters = [
  "Saitama",
  "Genos",
  "Blast",
  "Tornado",
  "Bang",
  "Atomic Samurai",
  "Child Emperor",
  "Metal Knight",
  "King",
  "Zombieman",
  "Drive Knight",
  "Pig God",
  "Superalloy Blackluster",
  "Watchdog Man",
  "Flashy Flash",
  "Tank-Top Master",
  "Metal Bat",
  "Puri-Puri Prisoner",
  "Amai Mask",
  "Snakebite Snek",
  "Golden Ball",
  "Spring Mustachio",
  "Lightning Max",
  "Stinger",
  "Iaian",
  "Okama Itachi",
  "Bushi Drill",
  "Heavy Tank Loincloth",
  "Blue Fire",
  "Magicman",
  "Smileman",
  "Lightning Genji",
  "Heavy Kong",
  "Peach Terry",
  "Chain Toad",
  "Tank-Top Blackhole",
  "Blizzard",
  "Eyelashes",
  "Wild Monkey",
  "Triple-Staff Lilly",
  "Mushroom",
  "Jet Niceguy",
  "Pineapple",
  "Darkness Blade",
  "Bones",
  "Mumen Rider",
  "Tank-Top Tiger",
  "Staff members",
  "Agoni",
  "Sitch",
  "Narinki",
  "Vaccine Man",
  "Crablante",
  "Fukegao",
  "Marugori",
  "Subterraneans",
  "Mosquito Girl",
  "Doctor Genus",
  "Armored Gorilla",
  "Carnage Kabuto",
  "Manty",
  "Slugerous",
  "Frog Man",
  "Ground Dragon",
  "Beast King",
  "Hammerhead",
  "Speed-o'-Sound Sonic",
  "Kombu Infinity",
  "Deep Sea King",
  "The Sky King",
  "Boros",
  "Melzargard",
  "Groribas",
  "Geryuganshoop",
  "Garo",
  "Monster King Orochi",
  "Centikohai",
  "Martial Gorilla",
  "Rhino Wrestler",
  "Monster Princess Super S",
  "Gouketsu",
  "Tempest Wind",
  "Gyoro-Gyoro",
  "Kuseno",
  "Zeniru",
  "Shibabawa",
  "Charanko",
  "Bomb",
  "Sourface",
  "Suiryu"
];

export default characters;
